### PR TITLE
Splitted react-jsx into react and jsx-to-markup

### PR DESCRIPTION
**Pull request by KnisterPeter**
This is a complete rewrite of the react-jsx transformer.
There is no API break and the change offers to create
common.js modules from patterns without rendering
static markup.

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Don't merge until tested with current projects.

**Comment by Dangoo** [comment]
The compile queue doesn't use browserify/babelify yet so Stage-0-Features don't work.
An attempt to chain the jsx content through browserify before taking it to react react-to-markup didn't work out either.

**Comment by KnisterPeter** [comment]
@Dangoo what do you mean by 'don't use browserify/babelify'? The new react transformer just create a valid react component from a pattern.
The react-to-markup transform uses babel-core to transpile your code. Maybe there is some config for the transformer missing so stage-0 could be enabled. But it shouldn't be enabled by default.

**Comment by Dangoo** [comment]
In the current implementation stage 2 is the default for babel and could be easily overwritten by adding a transforms.js in the mypatternate/configuration/patternplate-server folder and configure the transformer options by using the same tree structure as in the patternplate-server. This doesn't work anymore with the new jsx-transformer.

**Comment by KnisterPeter** [comment]
@Dangoo The latest commit should fix the missing configuration and enable stage-0 on request.

**Comment by KnisterPeter** [comment]
@Dangoo, @levito, @opatut, @marionebl Please check this server pull against your projects so this does not break anything.

@Dangoo: You should be able to use any import/require from node_modules in your jsx pattern now.

@marionebl: Please review the code for any problems.

**Comment by Dangoo** [comment]
Enable stage 0 is required but does not work since whitelisting blocks stage0 feature enabling.

**Comment by KnisterPeter** [comment]
@Dangoo: Please recheck. You have to set the stage-0 opts for the react transformer as well as for the react-to-markup transformer.

**Comment by levito** [comment]
@KnisterPeter: I get the following error in patterns which depend on other patterns:

```
error: [patternplate-server] Error in "atoms/avatar" during transform "react" of "/Users/.../index.jsx": unknown: Unexpected token (16:0)
debug: [patternplate-server] SyntaxError: unknown: Unexpected token (16:0)
  14 | </div>
  15 |
> 16 | );
     | ^
  17 |
  18 |  }
  19 | }
```

**Comment by KnisterPeter** [comment]
@levito: Should be fixed. Please retest

**Comment by levito** [comment]
@KnisterPeter the above error is fixed, but a previous feature is missing. Originally, I could set the context option in an `@environments` pattern:

```
    "react-jsx": {
      "opts": {
        "context": {
          "foo": "bar"
        }
      }
    }
```

Now `this.context.foo` is undefined.

I also tried setting it for "react", this doesn't work either.

**Comment by KnisterPeter** [comment]
@levito I've added a config like this to simulate this hack. But there is a breaking change required on the configuration.
Please update your config to match this structure:

```
"react-jsx": {
  "opts": {
    "globals": {
      "context": {
        "foo": "bar"
      }
    }
  }
}
```

**Comment by KnisterPeter** [comment]
@levito, @Dangoo, @opatut To test this pull requests you could also do 'npm install patternplate-server@beta' (or even 'npm install patternplate@beta')

**Pull request merged**
